# Site settings
title: Lauren Armbrust
description: Junior Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://larmflower.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: larmflower
user_description: A description of my experiences.
user_title: Web Developer
email: laurenarmbrust@gmail.com
twitter_username: lnarosetta
github_username:  larmflower


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
